### ISSUE TITLE
Make pages for poetry and stand up

### ISSUE THREAD

**Issue by keshav1245** [keshav1245/apratim2019#96]
Rules for stand up comedy
.It is a solo event 
.Time limit is 5-7 minutes
. Negative marking for exceeding the time limit
. Any kind of cuss words are strictly prohibited
.content should be  original
. Use of any kind of chits or  mobile phones are not allowed
. Decision of judges will be final and binding

Rules for poetry
. It is a solo event 
. Time limit is 3-5 min
. Negative marking for exceeding the time limit
. Languages that can be used are Hindi English Punjabi and hindustani.
. Content should be original

**Comment by CO18353** [comment]
On It

**Comment by keshav1245** [comment]
@CO18353 Ok Bro thanks :D
